# Generated by Django 5.2.1 on 2026-06-19 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('resume_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=255, null=True)),
                ('github', models.CharField(blank=True, max_length=255, null=True)),
                ('objective', models.TextField(blank=True, null=True)),
                ('selected_template', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('theme_color', models.CharField(blank=True, default='#2563EB', max_length=50, null=True)),
                ('font_choice', models.CharField(blank=True, default='sans', max_length=50, null=True)),
                ('density_option', models.CharField(blank=True, default='20', max_length=10, null=True)),
                ('display_photo', models.BooleanField(default=True)),
                ('highlight_skills', models.BooleanField(default=True)),
                ('photo_data_url', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'resume',
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_title', models.CharField(blank=True, max_length=150, null=True)),
                ('project_description', models.TextField(blank=True, null=True)),
                ('technologies', models.CharField(blank=True, max_length=255, null=True)),
                ('role', models.CharField(blank=True, max_length=150, null=True)),
                ('duration', models.CharField(blank=True, max_length=100, null=True)),
                ('resume', models.ForeignKey(db_column='resume_id', on_delete=django.db.models.deletion.CASCADE, related_name='projects_list', to='resume_builder.resume')),
            ],
            options={
                'db_table': 'projects',
            },
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('language_id', models.AutoField(primary_key=True, serialize=False)),
                ('language_name', models.CharField(blank=True, max_length=100, null=True)),
                ('resume', models.ForeignKey(db_column='resume_id', on_delete=django.db.models.deletion.CASCADE, related_name='languages_list', to='resume_builder.resume')),
            ],
            options={
                'db_table': 'languages',
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('experience_id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(blank=True, max_length=150, null=True)),
                ('company', models.CharField(blank=True, max_length=150, null=True)),
                ('duration', models.CharField(blank=True, max_length=100, null=True)),
                ('bullets', models.TextField(blank=True, null=True)),
                ('resume', models.ForeignKey(db_column='resume_id', on_delete=django.db.models.deletion.CASCADE, related_name='experience_list', to='resume_builder.resume')),
            ],
            options={
                'db_table': 'experience',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('education_id', models.AutoField(primary_key=True, serialize=False)),
                ('institution', models.CharField(max_length=150)),
                ('degree', models.CharField(blank=True, max_length=100, null=True)),
                ('specialization', models.CharField(blank=True, max_length=100, null=True)),
                ('passing_year', models.CharField(blank=True, max_length=50, null=True)),
                ('percentage', models.CharField(blank=True, max_length=50, null=True)),
                ('resume', models.ForeignKey(db_column='resume_id', on_delete=django.db.models.deletion.CASCADE, related_name='education_list', to='resume_builder.resume')),
            ],
            options={
                'db_table': 'education',
            },
        ),
        migrations.CreateModel(
            name='Certifications',
            fields=[
                ('certification_id', models.AutoField(primary_key=True, serialize=False)),
                ('certification_name', models.CharField(blank=True, max_length=150, null=True)),
                ('issuer', models.CharField(blank=True, max_length=150, null=True)),
                ('certification_year', models.CharField(blank=True, max_length=50, null=True)),
                ('resume', models.ForeignKey(db_column='resume_id', on_delete=django.db.models.deletion.CASCADE, related_name='certifications_list', to='resume_builder.resume')),
            ],
            options={
                'db_table': 'certifications',
            },
        ),
        migrations.CreateModel(
            name='Achievements',
            fields=[
                ('achievement_id', models.AutoField(primary_key=True, serialize=False)),
                ('achievement_description', models.TextField(blank=True, null=True)),
                ('resume', models.ForeignKey(db_column='resume_id', on_delete=django.db.models.deletion.CASCADE, related_name='achievements_list', to='resume_builder.resume')),
            ],
            options={
                'db_table': 'achievements',
            },
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('skill_id', models.AutoField(primary_key=True, serialize=False)),
                ('skill_name', models.CharField(blank=True, max_length=100, null=True)),
                ('resume', models.ForeignKey(db_column='resume_id', on_delete=django.db.models.deletion.CASCADE, related_name='skills_list', to='resume_builder.resume')),
            ],
            options={
                'db_table': 'skills',
            },
        ),
    ]
